project_id = "ietjmyrelhijxyozcequ"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
enable_signup = true

[db]
port = 54322

[functions.whatsapp-connect]
verify_jwt = true

[functions.whatsapp-send-message]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.save-zapi-config]
verify_jwt = true