project_id = "ietjmyrelhijxyozcequ"

[functions.judit-carregar-detalhes-lote]
verify_jwt = true

[functions.escavador-ativar-e-buscar]
verify_jwt = true

[functions.escavador-webhook]
verify_jwt = false

[functions.escavador-consulta-recorrente]
verify_jwt = false

[functions.judit-buscar-processo]
verify_jwt = true

[functions.judit-ativar-monitoramento]
verify_jwt = true

[functions.judit-desativar-monitoramento]
verify_jwt = true

[functions.judit-webhook]
verify_jwt = false

[functions.judit-buscar-por-oab]
verify_jwt = true

[functions.judit-sincronizar-oab]
verify_jwt = true

[functions.judit-buscar-detalhes-processo]
verify_jwt = true

[functions.judit-ativar-monitoramento-oab]
verify_jwt = true

[functions.judit-webhook-oab]
verify_jwt = false

[functions.judit-consultar-request]
verify_jwt = true

[functions.judit-consultar-detalhes-request]
verify_jwt = true

[functions.judit-buscar-processo-cnj]
verify_jwt = true

[functions.create-tenant-with-admin]
verify_jwt = false

[functions.judit-baixar-anexo]
verify_jwt = true

[functions.delete-tenant]
verify_jwt = true
