project_id = "ietjmyrelhijxyozcequ"

[functions.escavador-ativar-e-buscar]
verify_jwt = true

[functions.escavador-webhook]
verify_jwt = false

[functions.escavador-consulta-recorrente]
verify_jwt = false
