project_id = "ietjmyrelhijxyozcequ"

[functions.escavador-ativar-e-buscar]
verify_jwt = true

[functions.escavador-webhook]
verify_jwt = false

[functions.escavador-consulta-recorrente]
verify_jwt = false

[functions.judit-buscar-processo]
verify_jwt = true

[functions.judit-ativar-monitoramento]
verify_jwt = true

[functions.judit-desativar-monitoramento]
verify_jwt = true

[functions.judit-webhook]
verify_jwt = false

[functions.judit-buscar-por-oab]
verify_jwt = true
